### ISSUE TITLE
No such file or directory: ... NYSE_dates.txt

### ISSUE THREAD

**Issue by slavasav** [blacksburg98/finpy#1]
Hi,

Was trying out the finpy module. The first observation is that it requires version 2.7 precisely, which is a rather strong requirement. Next, when import finpy.utils or finpy.equity I am getting this error:
  File "<stdin>", line 1, in <module>
  File "/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/utils.py", line 8, in <module>
    from equity import Equity
  File "/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/equity.py", line 13, in <module>
    import finpy.fpdateutil as du
  File "/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/fpdateutil.py", line 38, in <module>
    GTS_DATES = _cache_dates()
  File "/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/fpdateutil.py", line 32, in _cache_dates
    datestxt = np.loadtxt(filename, dtype=str)
  File "/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 737, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/NYSE_dates.txt'

**Comment by blacksburg98** [comment]
Can you check whether '/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/NYSE_dates.txt' exists?

**Comment by slavasav** [comment]
Hi, No, it does not exist in the path mentioned. Slava 29.11.2014, 18:59, "blacksburg98" notifications@github.com:Can you check whether '/Users/slava.savitskiy/.pyenv/versions/2.7/lib/python2.7/site-packages/finpy/NYSE_dates.txt' exists?—Reply to this email directly or view it on GitHub.

**Comment by blacksburg98** [comment]
How do you install it?

**Comment by slavasav** [comment]
simply, pip install finpy. Had to use exactly python 2.7, otherwise pip would complain that dependency python==2.7 could not be satisfied. 29.11.2014, 23:41, "blacksburg98" notifications@github.com:How do you install it?—Reply to this email directly or view it on GitHub.

**Comment by blacksburg98** [comment]
I've just ported it to 3.4. You can try it. I use pip to install and do not see this problem. I've also updated setup.py.

**Comment by slavasav** [comment]
Now it works, thanks. Slava 30.11.2014, 19:41, "blacksburg98" notifications@github.com:I've just ported it to 3.4. You can try it. I use pip to install and do not see this problem. I've also updated setup.py.—Reply to this email directly or view it on GitHub.
